### ISSUE TITLE
Undefined local variable or method

### ISSUE THREAD

**Issue by denandreychuk** [sweatco/xcode-archive-cache#30] opened 2021-07-12 11:28 UTC
/Library/Ruby/Gems/2.6.0/gems/xcode-archive-cache-0.0.10/lib/injection/injector.rb:244:in `find_build_configuration': undefined local variable or method `node' for #<XcodeArchiveCache::Injection::Injector:0x00007fbf53204dc8> (NameError)

**Comment by Ilushkanama** [comment] 2021-07-14 14:41
Hey @denandreychuk, while the cause of this issue is pretty apparent (and seems to be fixed by #31), I believe there are more problems besides the original one.  Could you please provide a sample project which I can use to reproduce the issue?

**Closed** 2021-07-14 15:11 UTC
