### ISSUE TITLE
Support caching of bundle files

### ISSUE THREAD

**Issue by Berdikhan** [sweatco/xcode-archive-cache#2] opened 2019-07-18 08:49 UTC
Thanks for such a great tool (even though I still wasn't able to make it work).

One of my dependencies has `*.bundle` along with `*.framework`, most of the functions in your gem are failing because of bundle file, I assume it's expecting static & dynamic frameworks, not bundle. Not sure how to cache it. 

```
Traceback (most recent call last):
	16: from /Users/berdikhan/.rbenv/versions/2.6.3/bin/xcode-archive-cache:23:in `<main>'
	15: from /Users/berdikhan/.rbenv/versions/2.6.3/bin/xcode-archive-cache:23:in `load'
	14: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/bin/xcode-archive-cache:11:in `<top (required)>'
	13: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/command/command.rb:19:in `run'
	12: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	11: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/command/inject.rb:48:in `run'
	10: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:46:in `run'
	 9: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:46:in `each'
	 8: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:47:in `block in run'
	 7: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:71:in `handle_target'
	 6: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:71:in `each'
	 5: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:72:in `block in handle_target'
	 4: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:97:in `handle_dependency'
	 3: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:130:in `rebuild_if_needed'
	 2: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:130:in `each'
	 1: from /Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/runner/runner.rb:133:in `block in rebuild_if_needed'
/Users/berdikhan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/xcode-archive-cache-0.0.6/lib/build/product_extractor.rb:16:in `list_product_contents': private method `select' called for nil:NilClass (NoMethodError)
```

**Comment by Berdikhan** [comment] 2019-07-18 08:50
This is how it looks like
<img width="468" alt="Screenshot 2019-07-18 at 4 50 18 PM" src="https://user-images.githubusercontent.com/11346086/61443468-24cd8b80-a97c-11e9-9086-be7a346e15e7.png">

**Comment by Berdikhan** [comment] 2019-07-18 11:38
Ok, I was able to hack around and ignore bundle files for now, but there is a different problem:

- I have 2 targets:
```
workspace "fave" do
  configuration "Test_Debug" do
    build_configuration "Debug"
    xcodebuild_args "SOME_FLAG='1' -UseModernBuildSystem=NO"
  end

  derived_data_path "build"

  target "fave" do
    cache "Pods_fave.framework"    
  end
  
  target "NotificationService" do
    cache "Pods_NotificationService.framework"
  end

end
```
For some reason, while caching app's pods, it's caching NotificationService's pods as well, so when it starts caching NotificationService's pods, it's failing.

**Comment by Ilushkanama** [comment] 2019-07-20 17:47
Hey @Berdikhan, thanks for reporting this.

You're right about bundles - we don't support them at the moment. Adding support would require some additional research, so I'll give an ETA in a couple days after doing the research.

Second issue you encountered looks like it's caused by pods that are shared by "fave" and "NotificationService".  Do you use shared pods for those targets? Shared pod targets are going to be removed after "Pods_fave.framework" archiving, and archiving of "Pods_NotificationService.framework" should fail due to missing dependencies.

**Comment by Berdikhan** [comment] 2019-07-21 15:28
After doing some research I found out that dependencies of NotificationExtension target are being linked to main app's target. Will update if I will find a workaround

**Comment by Ilushkanama** [comment] 2019-07-21 17:39
I'm sure this is a serious issue that should be fixed. It would help a lot if you share contents of the Podfile.

**Comment by Berdikhan** [comment] 2019-07-22 03:51
I was able to replicate it with fresh new app, here is my Podfile:
```
target 'TestArchive' do
  platform :ios, '9.0'
  use_frameworks!

  pod 'CleverTap-iOS-SDK', '3.6.0'
  pod 'MoEngage-iOS-SDK', '3.3.1'

  target 'TestArchiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NotificationService' do
  platform :ios, '10.0'
  use_frameworks!
  pod 'MORichNotification', '1.3.0'
  pod 'CTNotificationService', '0.1.1'
end

```

**Comment by Ilushkanama** [comment] 2019-07-22 11:21
Thanks. I was able to reproduce it too, and from my point of view we have two problems here:
1. XcodeArchiveCache needs to merge build graphs for all target+dependency pairs to correctly inject cached products in all build graphs. That's what you discovered with the podfile you shared. Build graph for fave's dependency `Pods_fave.framework` should be merged with build graph for NotificationService's `Pods_NotificationService.framework`.
2. XcodeArchiveCache needs to inject cached products to dependent targets that aren't mentioned in any build graph from Cachefile. In terms of the podfile you shared, if we remove NotificationService target from Cachefile, `CTNotificationService` target is going to be deleted after `Pods_fave.framework` handling, breaking NotificationService build.

I created #5 and #6 to make these issues easier to discover and track. Both require a fair amount of work so I'll do my best to fix them this week.

**Comment by Berdikhan** [comment] 2019-07-25 10:00
Thank you so much, I will be happy to help you test.

**Comment by Ilushkanama** [comment] 2019-08-02 07:07
@Berdikhan could you please test `0.0.8.pre.2`? I've added support for bundle products and shared dependencies. You can install it with `gem install xcode-archive-cache --pre`.

**Comment by Berdikhan** [comment] 2019-08-02 07:16
`0.0.8.pre.1` is working on my test project (which has similar lighter pods, but similar target), but on my actual project still not working.
Will try `0.0.8.pre.2` now, will update you shortly.

**Comment by Berdikhan** [comment] 2019-08-02 10:25
`0.0.8.pre.2` works without any issue, but when I try to archive/compile, it's taking forever (until now I wasn't able to archive it). I am using `fastlane gym` to archive. Will update you if I can make it work

**Comment by Ilushkanama** [comment] 2019-08-08 06:17
That's strange, both `xcodebuild` and `fastlane gym` work well on a test project for me. Could you please post `fastlane` output?

**Comment by Berdikhan** [comment] 2019-08-09 09:48
I tried to add all my pods to an empty project, it is working, but in project with 1.5K source files, it's not. I don't think it is related to fastlane, I tried manual archive, still same. It stuck at compiling source files. Will update here if I can figure out.

**Closed** 2021-07-14 14:22 UTC
Labels: enhancement

**Comment by aehlke** [comment] 2025-02-08 10:28
Anyone get this working with Swift Package Manager / SPM?
